export const SCHEDUELE_LIST_REQUEST = 'SCHEDUELE_LIST_REQUEST';
export const SCHEDUELE_LIST_SUCCESS = 'SCHEDUELE_LIST_SUCCESS';
export const SCHEDUELE_LIST_FAIL = 'SCHEDUELE_LIST_FAIL';

export const SCHEDUELE_DETAILS_REQUEST = 'SCHEDUELE_DETAILS_REQUEST';
export const SCHEDUELE_DETAILS_SUCCESS = 'SCHEDUELE_DETAILS_SUCCESS';
export const SCHEDUELE_DETAILS_FAIL = 'SCHEDUELE_DETAILS_FAIL';

export const SCHEDUELES_LIST_MY_RESET = 'SCHEDUELES_LIST_MY_RESET';

export const SCHEDUELE_DELETE_REQUEST = 'SCHEDUELE_DELETE_REQUEST';
export const SCHEDUELE_DELETE_SUCCESS = 'SCHEDUELE_DELETE_SUCCESS';
export const SCHEDUELE_DELETE_FAIL = 'SCHEDUELE_DELETE_FAIL';

export const SCHEDUELE_CREATE_REQUEST = 'SCHEDUELE_CREATE_REQUEST';
export const SCHEDUELE_CREATE_SUCCESS = 'SCHEDUELE_CREATE_SUCCESS';
export const SCHEDUELE_CREATE_FAIL = 'SCHEDUELE_CREATE_FAIL';
export const SCHEDUELE_CREATE_RESET = 'SCHEDUELE_CREATE_RESET';

export const SCHEDUELE_UPDATE_REQUEST = 'SCHEDUELE_UPDATE_REQUEST';
export const SCHEDUELE_UPDATE_SUCCESS = 'SCHEDUELE_UPDATE_SUCCESS';
export const SCHEDUELE_UPDATE_FAIL = 'SCHEDUELE_UPDATE_FAIL';
export const SCHEDUELE_UPDATE_RESET = 'SCHEDUELE_UPDATE_RESET';
