export const SESSION_LIST_REQUEST = 'SESSION_LIST_REQUEST';
export const SESSION_LIST_SUCCESS = 'SESSION_LIST_SUCCESS';
export const SESSION_LIST_FAIL = 'SESSION_LIST_FAIL';

export const SESSION_DETAILS_REQUEST = 'SESSION_DETAILS_REQUEST';
export const SESSION_DETAILS_SUCCESS = 'SESSION_DETAILS_SUCCESS';
export const SESSION_DETAILS_FAIL = 'SESSION_DETAILS_FAIL';
